DigiChamps/Models/Teacher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiChamps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public decimal TeacherId { get; set; }
        public Nullable<int> Active { get; set; }
        public string Email { get; set; }
        public string fcmId { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> StageId { get; set; }
        public Nullable<System.Guid> SchoolId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public string Photo { get; set; }
    }
}

DigiChamps/Models/TestResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using System.Security.Authentication;
using System.Security.Cryptography;
using System.Web.Security;
using System.Text;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;


namespace DigiChamps.Models
{
    public class TestResult
    {
        public int Regd_ID { get; set; }
        public string Customer_Name { get; set; }

        public int Batch_Id { get; set; }
        public string Batch_Name { get; set; }

        public int Batch_Assign_Id { get; set; }
        public Nullable<int> Teach_ID { get; set; }
        public long Id { get; set; }

        public int Exam_ID { get; set; }
        public string Exam_Name { get; set; }
        public int Result_ID { get; set; }

        public Nullable<int> Board_Id { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string Subject { get; set; }

        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Question_Nos { get; set; }
        public Nullable<int> Question_Attempted { get; set; }
        public Nullable<int> Total_Correct_Ans { get; set; }
        public string Chapter { get; set; }
        public int ResultdtL_ID { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public string Question { get; set; }
        public string Qustion_Desc { get; set; }
        public string Answer_Desc { get; set; }
        public string Answer_Image { get; set; }
        public Nullable<int> Answer_ID { get; set; }
        public string Option_Desc { get; set; }
        public string Option_Image { get; set; }
        public Nullable<bool> Is_Correct { get; set; }
        public string Inserted_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}

DigiChamps/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using DigiChamps.Controllers;
using System.Web.Security;
using System.IO;
using System.Text;
using System.Net;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Mail;

namespace DigiChamps.Controllers
{
    public class TeacherController : Controller
    {
        DigiChampsEntities DbContext = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver().Date;

        #region-------------------------Teacher 1ststep-------------------------------
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult Login()
        {
            if (Session["USER_CODE"] != null)
            {
                if (Session["ROLE_CODE"].ToString() == "T")
                {
                    return RedirectToAction("TeacherDashboard");
                }
                else
                {
                    return RedirectToAction("Logout");
                }
            }
            else
            {
                if (Request.Cookies["Login"] != null)
                {
                    ViewBag.user = Request.Cookies["Login"].Values["user"];
                    ViewBag.Password = Request.Cookies["Login"].Values["Password"];
                }
                return View();
            }
        }
        [HttpPost]
        public ActionResult Login(string User_name, string password, string checkbox)
        {

            try
            {
                overdue();
                string pass_word = DigiChampsModel.Encrypt_Password.HashPassword(password);

                var obj = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_NAME == User_name && x.PASSWORD == pass_word && x.IS_ACCEPTED == true && x.ROLE_CODE == "T").FirstOrDefault();

                if (obj != null)
                {
                    if (obj.ROLE_CODE == "T")
                    {
                        var teacher = DbContext.tbl_DC_Teacher.Where(x => x.Email_ID == obj.USER_NAME && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                        if (teacher != null)
                        {
                            Session["USER_CODE"] = teacher.Teach_ID;
                            TempData["USER_CODE"] = teacher.Teach_ID;
                            Session["USER_NAME"] = obj.USER_NAME;
                            Session["ROLE_CODE"] = obj.ROLE_CODE;
                            Session["Time"] = today.ToShortTimeString();
                            Session["pfimage"] = teacher.Image;

                            FormsAuthentication.RedirectFromLoginPage(obj.USER_NAME, false);
                            if (checkbox != null)
                            {
                                HttpCookie cookie = new HttpCookie("Login");
                                cookie.Values.Add("user", User_name);
                                cookie.Values.Add("Password", password);
                                cookie.Expires = DateTime.Now.AddDays(10);
                                Response.Cookies.Add(cookie);
                            }
                            return RedirectToAction("TeacherDashboard");
                        }
                        else
                        {
                            TempData["ErrorMessage"] = "User Details does not exist, Please contact adminstrator.";
                            return View();
                        }
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Please login as a Teacher.";
                        return View();
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Invalid user name or password.";
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Something went wrong.";
            }
            return View();
        }
        public ActionResult Logout()
        {
            if (Session["USER_CODE"] != null)
            {
                logoutstatus(Convert.ToString(Session["USER_CODE"]));
            }
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ForgotPassword(string email)
        {
            string message;
            try
            {
                var find_mail = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_NAME == email && x.ROLE_CODE == "T").FirstOrDefault();
                if (find_mail != null)
                {
                    string password = CreateRandomPassword(6);
                    string t_password = DigiChampsModel.Encrypt_Password.HashPassword(password);

                    find_mail.PASSWORD = t_password;
                    DbContext.Entry(find_mail).State = EntityState.Modified;
                    DbContext.SaveChanges();
                    tbl_DC_Teacher obj = DbContext.tbl_DC_Teacher.Where(x => x.Email_ID == email).FirstOrDefault();
                    T_sendMail("T_F_PASS", email, password, email, obj.Teacher_Name);
                    message = "Login details successfully sent to the mailid.";
                }
                else
                {
                    message = "Mail id does not belongs to any teacher.";
                }
            }
            catch (Exception ex)
            {
                message = "Something went wrong.";
            }
            return Json(message);
        }
        public bool T_sendMail(string parameter, string username, string password1, string email, string name)
        {
            var getall = DbContext.SP_DC_Get_maildetails(parameter).FirstOrDefault();
            string eidTo = email;
            string mailtoshow = getall.SMTP_Email.ToString();
            string eidFrom = getall.SMTP_User.ToString();
            string Password = getall.SMTP_Pwd.ToString();
            string msgsub = "Digichamps Password Recovery";
            string hostname = getall.SMTP_HostName;
            string portname = getall.SMTP_Port.ToString();
            bool ssl_tof = true;
            string msgbody = getall.EmailConf_Body.ToString().Replace("{{name}}", name).Replace("{{username}}", username).Replace("{{password}}", password1);
            MailMessage greetings = new MailMessage();
            SmtpClient smtp = new SmtpClient();
            try
            {
                greetings.From = new MailAddress(mailtoshow, "DIGICHAMPS");//sendername
                greetings.To.Add(eidTo);//to whom
                greetings.IsBodyHtml = true;
                greetings.Priority = MailPriority.High;
                greetings.Body = msgbody;
                greetings.Subject = msgsub;
                smtp.Host = hostname;//host name
                smtp.EnableSsl = ssl_tof;//ssl
                smtp.Port = Convert.ToInt32(portname);//port
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential(eidFrom, Password);//from(user)//password
                smtp.Send(greetings);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        #region Auto_password
        public static string CreateRandomPassword(int PasswordLength)
        {
            string _allowedChars = "0123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ";
            Random randNum = new Random();
            char[] chars = new char[PasswordLength];
            int allowedCharCount = _allowedChars.Length;
            for (int i = 0; i < PasswordLength; i++)
            {
                chars[i] = _allowedChars[(int)((_allowedChars.Length) * randNum.NextDouble())];
            }
            return new string(chars);
        }
        #endregion
        [HttpGet]
        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ChangePassword(string Old_Password, string New_Password, string Conf_Password)
        {
            string message = string.Empty;
            if (Session["USER_CODE"] != null)
            {
                if (New_Password != "" && Conf_Password != "" && Old_Password != "")
                {

                    try
                    {
                        string u_code = Session["USER_CODE"].ToString();
                        string old_pass_word = DigiChampsModel.Encrypt_Password.HashPassword(Old_Password);
                        var data = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_CODE == u_code && x.PASSWORD == old_pass_word).FirstOrDefault();

                        if (data != null)
                        {
                            if (New_Password == Conf_Password)
                            {
                                string new_pass_word = DigiChampsModel.Encrypt_Password.HashPassword(New_Password).ToString();
                                var obj = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_CODE == u_code).FirstOrDefault();

                                obj.PASSWORD = new_pass_word;
                                DbContext.Entry(obj).State = EntityState.Modified;
                                DbContext.SaveChanges();
                                message = "0";
                            }
                            else
                            {
                                message = "1";

DigiChamps/Views/Teacher/AddRemark.cshtml
@{
    ViewBag.Title = "AddRemark";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

@using (Html.BeginForm("AddRemark", "Teacher", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", id = "validation-form" }))
{
    @Html.AntiForgeryToken();
    <div class="page-content-wrap">
        <div class="row ">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-file"></i> Add New</h3>
                    </div>
                    <input type="hidden" id="hid" name="hid" value="@ViewBag.id" />
                    <div class="box-content">

                        <div class="form-group">
                            <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Rating<span class="asterisk">*</span></label>
                            <div class="col-sm-9 col-lg-7 controls">
                                @if (ViewBag.id != null)
                                {
                                    <input type="text" name="txtRating" class="form-control" id="txttype" value="@ViewBag.Rating" data-rule-required="true" data-msg-required="Please Enter Rating" />
                                }
                                else
                                {
                                    <input type="text" name="txtRating" class="form-control" id="txttype" data-rule-required="true"/>
                                }

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Remark<span class="asterisk">*</span></label>
                            <div class="col-sm-9 col-lg-7 controls">
                                @if (ViewBag.id != null)
                                {
                                    <input type="text" name="txtRemark" class="form-control" id="txttype" value="@ViewBag.Remark" data-rule-required="true" data-msg-required="Please Enter Remark" />
                                }
                                else
                                {
                                    <input type="text" name="txtRemark" class="form-control" id="txttype" data-rule-required="true" />
                                }

                            </div>
                        </div>
                        <div class="form-group last box-tooll">
                            <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2">
                                <a href="@Url.Action("ViewRemark", "Teacher")" class="btn btn-primary"><i class="fa fa-undo"></i> <span> Back</span>  </a>
                                <button id="btnadd" type="submit" class="btn btn-primary btn-success"><i class="fa fa-check green-i"></i><span>Submit</span> </button>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>

}

DigiChamps/Views/Teacher/MentorStudentList.cshtml
@{
    ViewBag.Title = "View Student";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

@*<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-ticket"></i>Search Ticket By Date</h3>
            </div>
            <div class="box-content">
                <div class="page-content-wrap">
                    <div class="row">
                        <div class="">
                            @using (Html.BeginForm("Ticket_report", "Teacher", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="textfield5" class="col-sm-3 col-lg-5 control-label">From Date<span class="asterisk">*</span></label>
                                        <div class="col-sm-9 col-lg-7 controls">
                                            <input type="text" placeholder="@DateTime.Now.ToShortDateString()" autocomplete="off" data-rule-required="true" data-msg-required="Please select From date" name="f_Date" class="datepicker form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="textfield5" class="col-sm-3 col-lg-5 control-label">To Date<span class="asterisk">*</span></label>
                                        <div class="col-sm-9 col-lg-7 controls">
                                            <input type="text" placeholder="@DateTime.Now.ToShortDateString()" autocomplete="off" data-rule-required="true" data-msg-required="Please select To date" name="t_Date" class="datepicker form-control" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group last box-tooll">
                                        <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2">
                                            <button id="btnadd" type="submit" class="btn btn-primary"><i class="fa fa-search"></i><span> Search</span></button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>*@


<form id="Ticke_form" class="form-horizontal">
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-table"></i>View Students</h3>
                        <div class="box-tool box-tooll">
                            @*<a class="btn btn-large btn-primary" title="Refresh" href="/Teacher/Viewticekts"><i class="fa fa-refresh"></i> <span>Refresh</span></a>
                            <a class="btn btn-large btn-primary" title="My tickets" href="/Teacher/mytickets"><i class="fa fa-filter"></i> <span>My tickets</span></a>*@
                        </div>
                    </div>
                    <div class="box-content">
                        <div class="btn-toolbar pull-right clearfix">
                           @* <div class="btn-group">
                                <a class="btn btn-circle show-tooltip" title="Refresh" href="/Teacher/Viewticekts"><i class="fa fa-refresh"></i></a>
        <a class="btn btn-circle show-tooltip" title="My tickets" href="/Teacher/mytickets"><i class="fa fa-filter"></i></a>
    </div>*@
                        </div>
                        <br /><br />
                        <div class="clearfix"></div>
                        <div class="table-responsive" style="border:0">
                            <table class="table table-advance table-hover" id="table1">
                                <thead>
                                    <tr>
                                        <th hidden>Sl no</th>
                                        <th>Student Name</th>
                                        <th>Mobile</th>
                                        <th>Class</th>
                                        <th>Assigned Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.StudentTask != null)
                                    {
                                    int i=0;
                                        foreach (var item in ViewBag.StudentTask)
                                        {
                                            <tr>
                                                @{
                                                    DigiChamps.Models.DigiChampsEntities DbContext = new DigiChamps.Models.DigiChampsEntities();
                                                    int sid = Convert.ToInt32(@item.Student_ID);
                                                    var Studentdetails = DbContext.tbl_DC_Registration.Where(x => x.Regd_ID == sid).FirstOrDefault();
                                                    var registrationde = DbContext.tbl_DC_Registration_Dtl.Where(x => x.Regd_ID == sid).FirstOrDefault();
                                                    var ClassDetails = DbContext.tbl_DC_Class.Where(x => x.Class_Id == registrationde.Class_ID).FirstOrDefault();
                                                }
                                                <td hidden>@(i+=1)</td>
                                                <td>@Studentdetails.Customer_Name</td>
                                                <td>@Studentdetails.Mobile</td>
                                                <td>@ClassDetails.Class_Name</td>
                                                <td>@item.AssignDate</td>
                                                <td>@Html.ActionLink(" ", "Studenttaskdetails", "Teacher", new { id = @item.Student_ID }, new { @class = "btn btn-sm btn-primary show-tooltip fa fa-eye", @title = "View Tasks" })</td>
                                            </tr>
                                        }
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*<span class="badge">New</span>*@

    </div>
</form>

<div id="modal_3" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel2"><i class="fa fa-exclamation-triangle"></i>Message</h3>
            </div>
            <div class="modal-body">
                <h5></h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

<div id="modal_4" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel2"><i class="fa fa-exclamation-triangle"></i> Ticket Details</h3>
            </div>
            <div class="modal-body">
                <label for="textfield5" class="control-label">
                    Question<span class="asterisk">*</span>
                </label>
                <p id="Ticket_p"></p>

                <label for="textfield5" class="control-label">
                    Created on<span class="asterisk">*</span>
                </label><p id="Ticket_d"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
@*}*@
@section scripts
{
    <script>
        $(document).ready(function () {
            $(".blue").click(function () {
                debugger;
                $.ajax({
                    type: 'POST',
                    url: "/Teacher/tooltip_ticket_details",
                    data: { id: $(this).attr('value') },
                    dataType: "json",
                    success: function (data) {
                        if (data[0] == "No data found") {
                            $("#modal_4 .modal-body #Ticket_p").html(data[0]);
                            $("#modal_4 .modal-body #Ticket_d").html(data[0]);
                            $("#modal_4").modal("show");
                        } else {
                            $("#modal_4 .modal-body #Ticket_p").html(data[0]);
                            $("#modal_4 .modal-body #Ticket_d").html(data[1]);
                            $("#modal_4").modal("show");
                        }

                    }
                });
            });
        });
    </script>
    }

DigiChamps/Views/Teacher/RejectTicket.cshtml
@{
    ViewBag.Title = "Reject ticket";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

@using (Html.BeginForm("RejectTicket", "Teacher", FormMethod.Post, new { @class = "form-horizontal", id = "validation-form" }))
{
    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-file"></i>Reject Ticket</h3>
                       
                    </div>
                    <div class="box-content">
                            <div class="form-group">
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Remark<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                   @if (@ViewBag.remark != null)
                                   {
                                      
                                        <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" readonly>     @ViewBag.remark</textarea>
                                    }
                                   else
                                   {
                                       if (@ViewBag.status == "R"  )
                                       {
                                            <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject"  readonly>Question rejected</textarea>
                                       }
                                       else if(@ViewBag.status == "C")
                                       {
                                           <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject"  readonly>Question closed</textarea>
                                       }
                                       else
                                       {
                                            <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" data-rule-required="true" data-msg-required="Please enter remark"></textarea>
                                       }
                                   
                                   }
                                </div>
                            </div>
                       
                            <div class="form-group last">
                                <input type="hidden" value="@ViewBag.tkid" name="h_tkid" />
                                <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2 box-tooll ">
                                    @if (@ViewBag.status == "R"  || @ViewBag.status == "C")
                                    {
                                        
                                    }
                                    else
                                    {
    
                                         <button id="btnSearch" type="submit" name="Reject" class="btn btn-large btn-primary btn-success"><i class="fa fa-check green-i"></i> <span>Submit Remark</span></button>
                                    }
                                   <a class="btn btn-large btn-primary" title="Back" href="@Url.Action("ViewTickectDetail", "Teacher", new {id = @ViewBag.tkid })"><i class="fa fa-undo"></i> <span>Back</span></a>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    }