DigiChamps/Models/Orderdetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigiChamps.Models
{
    public class Orderdetails
    {
        public class orders
        {
          //  public Nullable<int> OrderPkg_ID { get; set; }
            //public Nullable<int> Package_ID { get; set; }
            //public string Package_Name { get; set; }
            //public string Package_Desc { get; set; }
            //public Nullable<System.DateTime> Expiry_Date { get; set; }
            //public string Board_Name { get; set; }
            //public string Class_Name { get; set; }
            //public string Chapters { get; set; }
            //public string Regd_No { get; set; }
            //public string subjects { get; set; }
            //public string Customer_Name { get; set; }
            //public string Email { get; set; }
            //public string Mobile { get; set; }
            //public string Phone { get; set; }
            //public string Pincode { get; set; }
            //public string Address { get; set; }

            public int Order_ID { get; set; }
            public Nullable<System.DateTime> order_date { get; set; }
          
            public string Order_No { get; set; }
            public Nullable<int> Regd_ID { get; set; }
            public Nullable<decimal> tax_Amt { get; set; }
            public Nullable<decimal> Total { get; set; }
            public int Count { get; set; }

            public string Discount { get; set; }

            public decimal? Grand_Total { get; set; }
        }
        public class success
        {
            public List<orders> order { get; set; }

        }
        public class getorders
        {
            public success success { get; set; }
        }

        public class Errorresult
        {
            public Errorresponse Error { get; set; }
        }
        public class Errorresponse
        {
            public string Message { get; set; }
        }


    }
}

DigiChamps/Models/PackagePreviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using System.Security.Authentication;
using System.Security.Cryptography;
using System.Web.Security;
using System.Text;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace DigiChamps.Models
{
    public class PackagePreviewModel
    {
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }

        public int Regd_ID { get; set; }
        public string Regd_No { get; set; }
        public string Customer_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }

        public int RegdDtl_ID { get; set; }
        public string Year { get; set; }

        public int PackageDtl_ID { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<int> Board_Id { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public string Class_Name { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Chapter_Id { get; set; }
        public string Chapter { get; set; }

        public string Package_Name { get; set; }
        public string Package_Desc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Total_Chapter { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Subscripttion_Period { get; set; }
        
        public int PackageSubDtl_ID { get; set; }
        public Nullable<int> SubScription_Limit { get; set; }

        public int Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Desc { get; set; }
        public string Module_Content { get; set; }
        public string Module_video { get; set; }
        public DateTime? Inserted_Date { get; set; }
        public Nullable<bool> Is_Offline { get; set; }

        public int? Tablet_Id { get; set; }

        public int DIYVideo_ID { get; set; }
        public string DIYVideo_Name { get; set; }
        public string DIYVideo_Upload { get; set; }
        public string DIYVideo_Description { get; set; }
    }
}

DigiChamps/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using DigiChamps.Models;

namespace DigiChamps.Controllers
{
    public class FAQController : ApiController
    {
        DigiChampsEntities db = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        public class ErrorResult
        {
            public ErrorResponse Error { get; set; }
        }

        public class ErrorResponse
        {
            public string Message { get; set; }
        }

        public class SuccessResponse
        {
            public string Message { get; set; }
        }
        public class SuccessResult
        {

            public List<FAQ> Faqs { get; set; }
        }


        public class FAQ
        {
            public int? FAQ_Id { get; set; }
            public string Answer { get; set; }
            public string Question { get; set; }



        }

        public class FAQ_List
        {
            public List<FAQ> list { get; set; }
        }
        public class success_FAQ
        {
            public FAQ_List Success { get; set; }
        }
        public class Errorresult
        {
            public Errorresponse Error { get; set; }
        }
        public class Errorresponse
        {
            public string Message { get; set; }
        }
        [HttpGet]
        public HttpResponseMessage GetFAQ()
        {
            try
            {
                var obj = new success_FAQ
                {
                    Success = new FAQ_List
                    {
                        list = (from c in db.tbl_DC_FAQs.Where(x => x.Is_Active == true && x.Is_Deleted == false)
                                select new FAQ
                                {

                                    FAQ_Id = c.FAQs_ID,
                                    Answer = c.FAQ_Answer,
                                    Question = c.FAQ
                                }).ToList(),

                    }
                };

                return Request.CreateResponse(HttpStatusCode.OK, obj);
            }
            catch (Exception)
            {

                var obj = new Errorresult
                {
                    Error = new Errorresponse
                    {
                        Message = "Something went wrong."
                    }
                };
                return Request.CreateResponse(HttpStatusCode.OK, obj);
            }
        }
    }
}

DigiChamps/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using DigiChamps.Models;
using DigiChamps.Controllers;
using System.Web.Security;
using System.IO;
using System.Text;
using System.Net;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Drawing.Imaging;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Collections.Specialized;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using CCA.Util;

namespace DigiChamps.Controllers
{
    [HandleError]
    public class StudentController : Controller
    {
        DigiChampsEntities DbContext = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");
            ViewBag.blog = DbContext.tbl_DC_Marketing_Blog.Where(x => x.Is_Active == true && x.Is_Deleted == false).ToList();
            ViewBag.team = DbContext.tbl_DC_Our_Team.Where(x => x.Is_Active == true && x.Is_Deleted == false).ToList();

            if (Session["USER_CODE"] != null)
            {
                if (Session["ROLE_CODE"].ToString() == "C")
                {
                    return RedirectToAction("studentdashboard", "student");
                }
                else
                {
                    return RedirectToAction("logout");
                }
            }
            return View();
        }
        [HttpPost]
        public JsonResult Index(string User_name, string password)
        {
            string msg = string.Empty;
            try
            {
                string pass_word = DigiChampsModel.Encrypt_Password.HashPassword(password);
                var obj = DbContext.tbl_DC_USER_SECURITY.Where(x => x.USER_NAME == User_name).FirstOrDefault();

                if (obj != null)
                {
                    if (obj.PASSWORD == pass_word)
                    {
                        if (obj.STATUS == "A")
                        {
                            if (obj.ROLE_CODE == "C")
                            {
                                if (obj.IS_ACCEPTED == true)
                                {
                                    Session["USER_CODE"] = obj.USER_CODE;
                                    Session["USER_NAME"] = obj.USER_NAME;
                                    Session["ROLE_CODE"] = obj.ROLE_CODE;
                                    TempData["USER_NAME"] = obj.USER_NAME;
                                    Session["Time"] = today.ToShortTimeString();
                                    ///  FormsAuthentication.RedirectFromLoginPage(obj.USER_NAME, false);
                                    string mm = Session["USER_CODE"].ToString();
                                    var _student_details = DbContext.tbl_DC_Registration.Where(x => x.Mobile == mm).FirstOrDefault();
                                    int sreg_id = Convert.ToInt32(_student_details.Regd_ID);
                                    var chkbrd_cls = DbContext.tbl_DC_Registration_Dtl.Where(x => x.Regd_ID == sreg_id && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                                    if (chkbrd_cls == null)
                                    {
                                        msg = "0"; //choose board
                                    }
                                    else
                                    {
                                        Session["class"] = chkbrd_cls.Class_ID;
                                        msg = "1"; //board already there
                                    }
                                }
                                else
                                {
                                    msg = "-5";
                                }
                            }
                            else
                            {
                                msg = "Please login as a student.";
                            }
                        }
                        else
                        {
                            msg = "-1"; //otp conformation
                        }
                    }
                    else
                    {
                        msg = "-3"; // "Password doesnot match.";
                    }
                }
                else
                {
                    msg = "-4";   // "User name is not yet registered.";
                }
            }
            catch (Exception ex)
            {
                ex.Message.ToString();
                msg = "-2";
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult letsbegin(string mobno)
        {
            string msg = string.Empty;
            string msg1 = string.Empty;
            try
            {
                if (mobno != null)
                {
                    var data = DbContext.tbl_DC_Registration.Where(x => x.Mobile == mobno && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                    if (data != null)
                    {
                        msg = "1"; //Number registered and redirect to login page
                        ViewBag.number = data.Mobile;
                    }
                    else
                    {
                        msg = "2"; //Number not registered and redirect to sign up page

                        ViewBag.number = mobno;
                    }
                }
            }
            catch (Exception ex)
            {
                msg = "0"; // Something went wrong
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult PrivacyPolicy()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");

            return View();
        }


        [HttpGet]
        public ActionResult Pricing()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");

            return View();
        }

        [HttpGet]
        public ActionResult TermsAndConditions()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");


            return View();
        }
        [HttpGet]
        public ActionResult RefundsAndCancellation()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");


            return View();
        }
        [HttpGet]
        public ActionResult contact()
        {
            ViewBag.Board_Id = new SelectList(DbContext.tbl_DC_Board.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Board_Id", "Board_Name");
            ViewBag.secureqsn = new SelectList(DbContext.tbl_DC_Security_Question.Where(x => x.Is_Active == true && x.Is_Deleted == false), "Security_Question_ID", "Security_Question");
            ViewBag.captcha = Createcaptcha(4);
            return View();
        }

        [HttpPost]
        public JsonResult contact(string fname, string lname, string email, string subject, string message, string captcha, string captcha_code)
        {
            string msg = string.Empty;
            try
            {
                if (captcha == captcha_code)
                {
                    StringBuilder sb = new StringBuilder();
                    sb.Append("<body style='margin: 0; padding: 0; border: none;'>");
                    sb.Append("<div style='width: 650px; float: left; border: 5px solid #CCC;color:rgba(255, 255, 255, 0.84); font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 22px; padding: 0; background-color: #36a8f5;'>");
                    sb.Append("<div style='width: 100%; float: left; background-color: #fff; padding: 10px 0px;'>");
                    sb.Append("<div style='margin-left: 20px; margin-right: 20px; background-color: #fff; padding: 0;text-align: center;'>");
                    sb.Append("<a href='http://learn.odmps.org'><img src='http://learn.odmps.org/Student_assets/images/digi-champ-logo.png' width='310' height='88' alt='DigiChamps' /></a>");

                    sb.Append("<div style='clear: both'>");
                    sb.Append("</div>");
                    sb.Append("</div>");
                    sb.Append("</div>");
                    sb.Append("<!-- background pic change  -->");
                    sb.Append("<div style='width: 100%; background-position: center bottom; padding: 0; border: none; float: left; background-size: cover'>");

DigiChamps/Views/Student/Student_questions.cshtml
@{
    ViewBag.Title = "My Questions";
    Layout = "~/Views/Shared/Student_layout_View1.cshtml";
}

<form id="Ticke_form" class="form-horizontal">
    <div class="page-content-wrap">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-table"></i>My Qusetions</h3>
                        <div class="box-tool">
                            <a title="Ask question" class="btn btn-primary" href="/Student/Askdoubt">Ask Question<i class="fa fa-question"></i></a>
                        </div>
                    </div>
                    <div class="box-content">
                        <div class="btn-toolbar pull-right clearfix">
                            <div class="btn-group">
                                <a class="btn btn-circle show-tooltip" title="Refresh" href="/Student/Student_questions"><i class="fa fa-refresh"></i></a>
                            </div>
                        </div>
                        <br /><br />
                        <div class="clearfix"></div>
                        <div class="table-responsive" style="border:0">
                            <table class="table table-advance table-hover" id="table1">
                                <thead>
                                    <tr>
                                        <th>Question Number</th>
                                        <th>Question</th>
                                        <td>Subject</td>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.studentallquestion != null)
                                    {

                                        foreach (var item in ViewBag.studentallquestion)
                                        {
                                            <tr>
                                                <td>@item.Ticket_No</td>
                                                <td>@item.Question</td>
                                                <td>@item.Subject</td>
                                                <td>
                                                    @Html.ActionLink(" ", "AnswerTicket", "Student", new { id = @item.Ticket_ID }, new { @class = "btn btn-sm btn-success show-tooltip fa fa-check", @title = "See answer and reply" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</form>

<div id="modal_3" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel2"><i class="fa fa-exclamation-triangle"></i>Message</h3>
            </div>
            <div class="modal-body">
                <h5></h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

<div id="modal_4" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel2"><i class="fa fa-exclamation-triangle"></i>Ticket Details</h3>
            </div>
            <div class="modal-body">
                <label for="textfield5" class="control-label">
                    Question <span class="asterisk">*</span>
                </label>
                <p id="Ticket_p"></p>

                <label for="textfield5" class="control-label">
                    Created on <span class="asterisk">*</span>
                </label><p id="Ticket_d"></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
@*}*@
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#btnSearch").click(function () {
                var tb = $(this).attr('title');
                var sel = false;
                var ch = $('#table1').find('tbody input[type=checkbox]');
                var c = confirm('Continue delete?');
                if (c) {

                    if ($('#table1').find('tbody input[type=checkbox]').is(':checked')) {
                        $.ajax({
                            type: 'POST',
                            url: "/Admin/Delete_ALLTickets",
                            data: $('#Ticke_form').serialize(),
                            success: function (data) {
                                if (data == "1") {
                                    location.href = "/Admin/Ticket";
                                    $("#modal_3 .modal-body h5").html("Selected Ticket Deleted.");
                                    $("#modal_3").modal("show");

                                } else {
                                    $("#modal_3 .modal-body h5").html("Something went wrong.");
                                    $("#modal_3").modal("show");
                                }
                            }
                        });


                    } else {
                        $("#modal_3 .modal-body h5").html("No data Selected.");
                        $("#modal_3").modal("show");
                    }

                }
            })
            $("#btnassign").click(function () {
                if ($('#table1').find('tbody input[type=checkbox]').is(':checked')) {
                    $.ajax({
                        type: 'POST',
                        url: "/Admin/Bulk_Assign_Tickets",
                        dataType: "json",
                        data: $('#Ticke_form').serialize(),
                        success: function (data) {
                            if (data == "1") {
                                location.href = "/Admin/Ticket";
                                $("#modal_3 .modal-body h5").html("Ticket Assigned Successfully.");
                                $("#modal_3").modal("show");

                            } else if (data == "2") {
                                $("#modal_3 .modal-body h5").html("Please select Teacher.");
                                $("#modal_3").modal("show");
                            }
                            else {
                                $("#modal_3 .modal-body h5").html("Something went wrong.");
                                $("#modal_3").modal("show");
                            }
                        }
                    });
                }
                else {
                    $("#modal_3 .modal-body h5").html("Please select data.");
                    $("#modal_3").modal("show");
                }
            })



            $(".blue").mouseenter(function () {

                $.ajax({
                    type: 'POST',
                    url: "/Admin/tooltip_ticket_details",
                    data: { id: $(this).attr('value') },
                    dataType: "json",
                    success: function (data) {
                        if (data[0] == "No data found") {
                            $("#modal_4 .modal-body #Ticket_p").html(data[0]);
                            $("#modal_4 .modal-body #Ticket_d").html(data[0]);
                            $("#modal_4").modal("show");
                        } else {
                            $("#modal_4 .modal-body #Ticket_p").html(data[0]);
                            $("#modal_4 .modal-body #Ticket_d").html(data[1]);
                            $("#modal_4").modal("show");
                        }

                    }
                });
            });
        });
    </script>
}

DigiChamps/Views/Student/orderdetails.cshtml
@model IEnumerable<DigiChamps.Models.SP_DC_Order_Details_Result>
@{
    ViewBag.Title = "Order Details | DIGICHAMPS | Learners Beyond Classrooms";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
}
<!-- Page Header -->
@section header{
    <i class="menu-icons order-detail-icon doubt-icon page_header_icon"></i>
    <span class="main-text">Order Details</span>
}
<!-- /pageheader -->

<div class="row">
    <div class="col-md-12 questions-cont">
        <!-- Question Panel Starts -->
        <div class="panel panel-ntspl">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Your Order Details
                </h3>
            </div>
            <div class="panel-body">
                @if (Model.Count() != 0)
                {

                    int i = 0; int j = 0;
                    foreach (var item in Model)
                        
                    {
                        
                         if(i % 4 == 0)
    {
        j = 1;               
        @*<div class='table-cont bd-clr-1'>*@

           }

         

           if (i % 4 == 1)
           {
               j = 2;
           }
            @*<div class='table-cont bd-clr-2'>*@

               
                if(i % 4 == 2)
                {
                    j = 3;
                }          
                    @*<div class='table-cont bd-clr-3'>*@


                if (i % 4 == 3)
                {
                    j = 4;
                }
                         <div class="bd-clr-@j">
                        <div class="panel panel-ntspl inner-panel">
                            <div class="panel-heading header-style">
                                <h3 class="panel-title">
                                    Order Number #@item.Order_No
                                    <span class="panel-options resbtn">
                                        <a href="/student/viewpackagedetail/@item.Package_ID">
                                            <button type="button" class="btn btn-blue btn-xs">View Package Details</button>
                                        </a>
                                    </span>
                                </h3>
                            </div>
                            <div class="panel-body test-panel-body pannel-padding">
                                <table class="table table-hover">
                                    <tbody>
                                        <tr>
                                            <th scope="row" class="td-width-one">Package Name</th>
                                            <td class="right-td td-width-two">@item.Package_Name</td>
                                        </tr>
                                        <tr>
                                            <th scope="row" class="td-width-one">Subjects</th>
                                            <td class="right-td td-width-two">@item.subjects</td>
                                        </tr>
                                        <tr>
                                            <td>Chapters</td>
                                            <td class="right-td">@item.Chapters</td>
                                        </tr>
                                        <tr>
                                            <td>Expire Date</td>
                                            <td class="right-td">@item.Expiry_Date</td>
                                        </tr>
                                        <tr>
                                            <td>Price</td>
                                            <td class="price-color small-bolt">INR @string.Format("{0:0.00}", item.Total) </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
                        i++;
                    }
                }
                else
                {
                    <div class="row">
                        <div class="col-md-12 questions-cont text-center">
                            <div class="ful-hi-wi">
                               <div class="no-content-notification">There are no ordered items.</div>
                                @*<img src="images/cartimg.png">*@
                                @{
                    DigiChamps.Models.DigiChampsEntities DbContext = new DigiChamps.Models.DigiChampsEntities();
                    var list = DbContext.tbl_DC_Sample_Image.Where(x => x.Image_Type == "Order" && x.Is_Active == true && x.Is_Deleted == false).FirstOrDefault();
                    ViewBag.list = list.Image_URL;
                            <img src="~/Images/SampleImage/@ViewBag.list" style="width:100%" class="img-responsive voffset3" />
                                }

                                <div class="foraddbtn">
                                    <a href="/student/packagepreview"><button type="button" class="btn btn-primary addbtn">BUY NOW</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                }

            </div>
        </div>
        <!-- Question Panel Ends -->
    </div>
</div>