DigiChamps/Controllers/TeacherAccessController.cs
using CrystalDecisions.Shared.Json;
using DigiChamps.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Drawing.Imaging;
//using static DigiChamps.Controllers.SchoolController;
//using static DigiChamps.Controllers.StudentController;

namespace DigiChamps.Controllers
{
    public class TeacherAccessController : Controller
    {
        DigiChampsEntities DbContext = new DigiChampsEntities();
        DateTime today = DigiChampsModel.datetoserver();

        public ActionResult Index()
        {                
        return RedirectToAction("Login");
        }
        #region ---------- Teacher rDashboard ------------
        public ActionResult TeacherDashboard()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }

        }
        #endregion

        #region -------------- Login --------------

        [HttpGet]
        public ActionResult Login()
        {           
         return View();            
        }


        [HttpPost]
        public ActionResult Login(string User_name, string password)
        {
            try
            {               
                var obj = DbContext.Teachers.Where(x => x.Mobile == User_name && x.Password == password).FirstOrDefault();

                if (obj != null)
                {
                    Session["TeacherId"] = obj.TeacherId;
                    Session["SchoolId"] = obj.SchoolId;
                    Session["Name"] = obj.Name;
                    Session["Email"] = obj.Email;
                    Session["Mobile"] = obj.Mobile;
                    Session["DepartmentName"] = obj.DepartmentName;
                    Session["Photo"] = obj.Photo;
                    Session["IsHead"] = obj.IsHead;

                    return RedirectToAction("TeacherDashboard");
                }
                else
                {
                    TempData["ErrorMessage"] = "Invalid credential for admin login.";
                    return View();

                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Something went wrong.";
            }
            return View();
        }
        #endregion

        #region ------------ MyProfile-------------------
        [HttpGet]
        public ActionResult MyProfile()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                var TeacherId = Convert.ToInt32(Session["TeacherId"]);
                Teacher _teachr = DbContext.Teachers.Where(x => x.TeacherId == TeacherId).FirstOrDefault();
                ViewBag.TeacherId = _teachr.TeacherId;
                ViewBag.Name = _teachr.Name;
                ViewBag.Email = _teachr.Email;
                //string date = Convert.ToString(_teachr.DateOfBirth).Substring(0, 10);
                //ViewBag.dateofbirth = date;
                ViewBag.Mobile = _teachr.Mobile;
                ViewBag.DepartmentName = _teachr.DepartmentName;
                ViewBag.IsHead = _teachr.IsHead;
                ViewBag.image = _teachr.Photo;
               
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
     
        [HttpPost]
        public ActionResult EditProfile(long TeacherId, HttpPostedFileBase Photo, string Name,string Mobile,string Email, string DepartmentName,string IsHead)
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                try
                {
                    var teacherid = Convert.ToInt32(Session["TeacherId"]);
                    var alldetail = DbContext.Teachers.Where(x => x.TeacherId ==TeacherId).FirstOrDefault();
                    string image = string.Empty;
                    if (alldetail != null)
                    {
                        alldetail.Name = Name;
                        alldetail.ModifiedOn = today;
                        alldetail.Mobile = Mobile;
                        alldetail.Email =Email;
                        alldetail.DepartmentName = DepartmentName;
                        if(IsHead=="on")
                        {
                            alldetail.IsHead = true;
                        }
                        else
                        {
                            alldetail.IsHead = false;
                        }
                        string guid = Guid.NewGuid().ToString();
                        if (Photo != null)
                        {
                            var fileName = Path.GetFileName(Photo.FileName.Replace(Photo.FileName.Split('.').FirstOrDefault().ToString(), guid.ToString()));
                            image = Convert.ToString(fileName);
                            var path = Path.Combine(Server.MapPath("~/Images/TeacherAccess/"), fileName);
                            Photo.SaveAs(path);
                            alldetail.Photo = image;
                        }

                        DbContext.Entry(alldetail).State = EntityState.Modified;
                        DbContext.SaveChanges();
                        TempData["SuccessMessage"] = " Successfully Edit Profile ";
                        return RedirectToAction("MyProfile");
                    }
                }
                catch
                {
                    return View();
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }


        [HttpGet]
        public ActionResult ChangePassword()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        [HttpPost]
        public ActionResult TeacherChangePassword(string Old_Password, string New_Password, string Conf_Password)
        {
            string message = string.Empty;
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null && username != "")
            {
                if (New_Password != "" && Conf_Password != "" && Old_Password != "")
                {              
                        var data = DbContext.Teachers.Where(x =>x.Password == Old_Password).FirstOrDefault();

                        if (data != null)
                        {
                            if (New_Password == Conf_Password)
                            {                                
                                data.Password = New_Password;
                                DbContext.Entry(data).State = EntityState.Modified;
                                DbContext.SaveChanges();
                                TempData["SuccessMessage"] = " Successfully Edit Profile ";
                                return RedirectToAction("ChangePassword");
                            }
                            else
                            {
                                TempData["ErrorMessage"] = " New Password And Confirm Password Did Not Match, ";
                                return RedirectToAction("ChangePassword");
                            }
                        }
                        else
                        {
                        TempData["ErrorMessage"] = "Please Enter Old Password, Did Not Match, ";
                        return RedirectToAction("ChangePassword");
                    }
                    

                }
                else
                {
                    TempData["WarningMessage"] = "Please Enter Password. ";
                    return RedirectToAction("ChangePassword");
                }
            }
            else
            {
                return RedirectToAction("Login");
            }
         
        }


        #endregion

        #region  ---------Logout --------------

        public ActionResult Logout()
        {           
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
        #endregion

        #region ------------Assigned Subject----------
        public ActionResult AssignedSubject()
        {
            var username = Convert.ToString(Session["Mobile"]);
            if (username != null  && username != "")
            {
         
            var teacherid = Convert.ToInt32(Session["TeacherId"]);
               var Schoollist = DbContext.tbl_DC_School_Info.Where(a => a.IsActive == true).ToList();
                var boardlist = DbContext.tbl_DC_Board.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
            var classlist = DbContext.tbl_DC_Class.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
            var sectionlist = DbContext.tbl_DC_Class_Section.Where(a => a.IsActive == true).ToList();
            var subjectlist = DbContext.tbl_DC_Subject.Where(a => a.Is_Active == true && a.Is_Deleted == false).ToList();
            var teacherslist = DbContext.Teachers.Where(a => a.Active == 1 ).ToList();
            var assignteacherlist = DbContext.tbl_DC_AssignSubjectToTeacher.Where(a => a.Is_Active == true && a.Teacher_ID == teacherid).ToList();
            var res = (from a in assignteacherlist
                       join b in teacherslist on a.Teacher_ID equals b.TeacherId

DigiChamps/Views/TeacherAccess/AssignedSubject.cshtml
@{
    ViewBag.Title = "AssignedSubject";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}
@model IEnumerable<DigiChamps.Models.AssignTeacherCls>

<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="~/TeacherAccess/TeacherDashboard">Home</a>
            <span class="divider"><i class="fa fa-angle-right"></i></span>
        </li>      
          <li class="active">Assigned Subject</li>        
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Assign Subject To Teacher List </h3>
                @*<div class="box-tool box-tooll">
                        <a class="btn btn-primary" href="/School/UploadAssignSubjectToTeacher"><i class="fa fa-upload"></i><span> Upload Excel</span></a>

                        <a class="btn btn-primary" href="/School/CreateAssignSubjectToTeacher"><i class="fa fa-plus"></i><span> Assign Subject</span></a>
                    </div>*@
            </div>
            <div class="box-content">

                <div class="table-responsive">
                    <table class="table table-advance" id="table1">

                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>School</th>
                                <th>Board</th>
                                <th>Class</th>
                                <th>Section</th>
                                <th>Subject</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int rowNo = 0;
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@(rowNo += 1)</td>
                                        <td>@item.SchoolName</td>
                                        <td>@item.BoardName</td>
                                        <td>@item.ClassName</td>
                                        <td>@item.SectionName</td>
                                        <td>@item.SubjectName</td>
                                        <td>
                                            @Html.ActionLink("View Student", "StudentDetails", "TeacherAccess", new { SectionId = @item.SectionId }, new { @class = "btn btn-sm btn-primary show-tooltip", @data_original_title = "View Student", @title = "View Student Details" })
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

DigiChamps/Views/TeacherAccess/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}


<div class="form-horizontal" id="validation-form">
    <form method="post" action="TeacherChangePassword">
        <div class="page-content-wrap">
            
            <div id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="~/TeacherAccess/TeacherDashboard">Home</a>
                        <span class="divider"><i class="fa fa-angle-right"></i></span>
                    </li>
                    <li class="active">Change Password</li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-title">
                            <h3><i class="fa fa-file"></i>Change Password</h3>
                        </div>
                        <div class="box-content">
                            <div class="form-group">
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Current Password<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <input type="password" placeholder="Current Password" class="form-control" name="Old_Password" id="Old_Password" data-rule-required="true" data-rule-minlength="6" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">New Password<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <input type="password" placeholder="New Password" class="form-control" name="New_Password" id="New_Password" data-rule-required="true" data-rule-minlength="6" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Confirm Password<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <input type="password" placeholder="Re-Enter Password" class="form-control" name="Conf_Password" id="Conf_Password" data-rule-required="true" data-rule-minlength="6" data-rule-equalto="#New_Password" />
                                </div>
                            </div>

                            <div class="form-group last box-tooll">
                                <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2">

                                    <button id="btnadd" type="submit" class="btn btn-primary btn-success"><i class="fa fa-check green-i"></i><span> Submit</span></button>

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END NEW RECORD -->
                </div>
            </div>
        </div>
    </form>
    </div>

DigiChamps/Views/TeacherAccess/Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Login - ODM Teacher</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/font-awesome/css/font-awesome.min.css">
    <!--page specific css styles-->
    <!--flaty css styles-->
    <link rel="stylesheet" href="~/css/flaty.css">
    <link rel="stylesheet" href="~/css/flaty-responsive.css">
    <link rel="shortcut icon" href="~/img/favicon.html">
    <style>
        .login-page form input[type="text"], .login-page form input[type="password"] {
    padding: 15px 10px !important;
    height: auto !important;
    font-size: 16px;    
    border: 1px solid #24a0d6;
    border-radius: 36px;
}

    </style>
           
</head>
<body class="login-page">
    <!-- BEGIN Main Content -->
    <div class="login-wrapper">
        <!-- BEGIN Login Form -->
        @using (Html.BeginForm("Login", "TeacherAccess", FormMethod.Post, new { @id = "validation-form" }))
        {
            <h3><img src="~/Images/digi1.jpg" height="40" width="40" />Teacher Login</h3>
            if (TempData["ErrorMessage"] != null)
            {
                <div style="font-size: 13px; color: red;">@TempData["ErrorMessage"]</div>
            }
            <hr />
            <div class="form-group">
                <div class="controls">
                    <input type="text" placeholder="Mobile" id="User_name" name="User_name" class="form-control" data-rule-required="true" data-msg-required="Please enter Mobile Number" />
                </div>
            </div>
            <div class="form-group">
                <div class="controls">
                    <input type="password" placeholder="Password" id="password" name="password" class="form-control" data-rule-required="true" data-msg-required="Please enter password" />
                </div>
            </div>

            <div class="form-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary form-control" style="box-shadow: inset 0px 1px 0px #2ab7ec, 0px 2px 0px 0px #31524d, 9px 14px 46px #2b6184;">LOGIN</button>
                </div>
            </div>
            <hr />
            <p class="clearfix">
                <a href="#" class="goto-forgot pull-left">Forgot Password?</a>

            </p>

        }
        <!-- END Login Form -->
        <!-- BEGIN Forgot Password Form -->
        @*@using (Html.BeginForm("ForgotPassword", "Admin", FormMethod.Post, new { @id = "form-forgot" }))
            {*@
        <form id="form-forgot" style="display:none">
            <h3><img src="~/Images/digi1.jpg" height="40" width="40" />Get your password</h3>
            <hr />
            <span id="frgmsg" style="color: #0090ff;"></span>
            <div class="form-group">
                <div class="controls">
                    <input type="email" placeholder="Email" class="form-control" id="t_mail" name="email" required />
                </div>
            </div>
            <div class="form-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary form-control">Recover</button>
                </div>
            </div>
            <hr />
            <p class="clearfix">
                <a href="/Admin/Login" class="goto-login pull-left">← Back to login form</a>
            </p>
        </form>
        @*}*@
        <!-- END Forgot Password Form -->
        <!-- BEGIN Register Form -->
       
        <!-- END Register Form -->
    </div>
    <!-- END Main Content -->
    <!--basic scripts-->
    <script src="~/assets/jquery/jquery-2.1.1.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <!--Validation scripts-->
    <script type="text/javascript" src="~/assets/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/assets/jquery-validation/dist/additional-methods.min.js"></script>


 
</body>
</html>

DigiChamps/Views/TeacherAccess/RejectTicket.cshtml
@{
    ViewBag.Title = "RejectTicket";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}

@using (Html.BeginForm("RejectTicket", "TeacherAccess", FormMethod.Post, new { @class = "form-horizontal", id = "validation-form" }))
{
    <div class="page-content-wrap">

        <div id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="~/TeacherAccess/TeacherDashboard">Home</a>
                    <span class="divider"><i class="fa fa-angle-right"></i></span>
                </li>
                <li>
                    <a href="~/TeacherAccess/TeacherTicket">Ticket</a>
                    <span class="divider"><i class="fa fa-angle-right"></i></span>
                </li>
                <li class="active">Reject Ticket</li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-ticket"></i>Reject Ticket</h3>

                    </div>
                    <div class="box-content">
                        <form action="#" class="form-horizontal form-bordered form-row-stripped">
                            <div class="form-group" hidden>
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Student Name<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <input type="text" id="Student_Name" name="Student_Name" class="form-control" value="@ViewBag.studentname" readonly />
                                    <input type="hidden" value="@ViewBag.tkid" name="h_tkid" />
                                </div>
                                <div class="col-sm-2">
                                    <div class="ajax-loader">
                                        <div class="loader"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Class<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <input type="text" id="Class_Name" name="Class_Name" value="@ViewBag.classname" class="form-control" readonly />
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Question Detail<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    <textarea class="form-control" rows="8" id="Question_Detail" name="Question_Detail" readonly>@ViewBag.question</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="textfield5" class="col-sm-3 col-lg-2 control-label">Remark<span class="asterisk">*</span></label>
                                <div class="col-sm-9 col-lg-7 controls">
                                    @if (@ViewBag.remark != null)
                                    {
                                        <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" readonly>  @ViewBag.remark</textarea>
                                    }
                                    else
                                    {
                                        if (@ViewBag.status == "R")
                                        {
                                            <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" readonly>Question rejected</textarea>
                                        }
                                        else if (@ViewBag.status == "C")
                                        {
                                            <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" readonly>Question closed</textarea>
                                        }
                                        else
                                        {
                                            <textarea class="form-control" rows="8" id="Remark_Reject" name="Remark_Reject" data-rule-required="true" data-msg-required="Please enter remark"></textarea>
                                        }
                                    }
                                </div>
                            </div>

                            <div class="form-group last">
                                <div class="col-sm-9 col-sm-offset-3 col-lg-7 col-lg-offset-2 box-tooll">
                                    @if (@ViewBag.status == "R" || @ViewBag.status == "C")
                                    {

                                    }
                                    else
                                    {
                                        <button id="btnSearch" type="submit" name="Reject" title="Click To Reject" class="btn btn-large btn-primary btn-danger"><i class="fa fa-times red-i"></i> Reject</button>


                                    }
                                    @*<a href="@Url.Action("ViewTickectDetail", "Admin", new { id = @ViewBag.tkid })" class="btn btn-inverse dropdown-toggle"><i class="fa fa-caret-left"></i> Back </a>*@
                                    <a class="btn btn-large btn-primary" title="Back To List" href="/TeacherAccess/ViewDoughtDetail/@ViewBag.tkid"><i class="fa fa-undo"></i> <span>Back</span></a>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>
}

DigiChamps/Views/TeacherAccess/StudentDetails.cshtml
@{
    ViewBag.Title = "StudentDetails";
    Layout = "~/Views/Shared/_TeacherAccessLayout.cshtml";
}

@model IEnumerable<DigiChamps.Controllers.TeacherAccessController.StudentDetails_Class>
    <div id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-home"></i>
                <a href="~/TeacherAccess/TeacherDashboard">Home</a>
                <span class="divider"><i class="fa fa-angle-right"></i></span>
            </li>
            <li class="active">
                <a href="~/TeacherAccess/AssignedSubject">Assigned Subject</a>
                <span class="divider"><i class="fa fa-angle-right"></i></span>
            </li>
            <li class="active">Subject Details</li>
        </ul>
    </div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-file"></i> Section Wise Student Details </h3>
                @*<div class="box-tool box-tooll">
                    <a class="btn btn-primary" href="/School/UploadAssignSubjectToTeacher"><i class="fa fa-upload"></i><span> Upload Excel</span></a>

                    <a class="btn btn-primary" href="/School/CreateAssignSubjectToTeacher"><i class="fa fa-plus"></i><span> Assign Subject</span></a>
                </div>*@
            </div>
            <div class="box-content">

                <div class="table-responsive">
                    <table class="table table-advance" id="table1">

                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>School</th>
                                <th>Class</th>
                                <th>Section</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int rowNo = 0;
                                foreach (var item in Model)
                                {
                            <tr>
                                <td>@(rowNo += 1)</td>
                                <td>@item.Customer_Name</td>
                                <td>@item.Mobile</td>
                                <td>@item.schoolname</td>
                                <td>@item.Class_Name</td>
                                <td>@item.SectionName</td>

                                @*<td>
            @Html.ActionLink("View Student", "StudentDetails", "TeacherAccess", new { SectionId = @item.SectionId }, new { @class = "btn btn-sm btn-info show-tooltip", @data_original_title = "View Student", @title = "View Student Details" })
        </td>*@
                            </tr>
                                }
                            }


                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>